name: flutter_firebase_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  cloud_firestore: ^3.1.5
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  firebase_performance: ^0.8.0+3
  firebase_remote_config: ^1.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flutterfire_ui: ^0.3.0
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^1.0.3
  package_info_plus: ^1.3.0
  shared_preferences: ^2.0.11
  state_notifier: ^0.7.1

dev_dependencies:
  auto_route_generator: ^3.2.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutterfire_cli: ^0.1.1+2
  freezed: ^1.1.0
  import_sorter: ^4.6.0
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
  generate: true # Enable generation of localized Strings from arb files.

import_sorter:
  ignored_files:
    - \/lib\/generated_plugin_registrant\.dart
    - .*.freezed\.dart
    - .*\.g\.dart
    - .*\.gen\.dart
    - .*\.gr\.dart
    - .*\.mocks\.dart

flutter_gen:
  output: lib/config