name: flutter_firebase_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  firebase_performance: ^0.8.0+3
  firebase_remote_config: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutterfire_cli: ^0.1.1+2
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
